# Generated by Django 5.2.5 on 2025-09-02 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_image_profile_profileid_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileid',
        ),
    ]
