# Generated by Django 5.2.5 on 2025-09-01 07:24

import knowledge.models.knowledge_base_models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('knowledge_base_id', models.CharField(max_length=36)),
                ('title', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=40)),
                ('storage_uri', models.CharField(max_length=255)),
                ('chunk_count', models.IntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('creater_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.CharField(default=knowledge.models.knowledge_base_models.generate_knowledge_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('owner_user_id', models.CharField(max_length=36)),
                ('name', models.CharField(default='我的知识库', max_length=100)),
                ('description', models.TextField(default='')),
                ('embed_model', models.CharField(default='0', max_length=80)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Markdown',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(default='123456', max_length=200)),
                ('content', models.CharField(max_length=350)),
                ('vector_id', models.CharField(blank=True, max_length=36, null=True)),
                ('number', models.IntegerField()),
                ('word_count', models.IntegerField()),
                ('document_id', models.CharField(max_length=36)),
                ('creater_id', models.CharField(max_length=36)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
