# Generated by Django 5.2.5 on 2025-09-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RagDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('source_type', models.CharField(max_length=64, null=True)),
                ('tags', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RagChunks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord', models.IntegerField()),
                ('content', models.CharField(max_length=350)),
                ('content_hash', models.CharField(max_length=64, unique=True)),
                ('split', models.CharField(max_length=16)),
                ('metadata', models.JSONField(null=True)),
                ('chunk_tags', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag0', models.CharField(max_length=64, null=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='knowledge.ragdocuments')),
            ],
            options={
                'indexes': [models.Index(fields=['doc', 'ord'], name='knowledge_r_doc_id_fc263b_idx'), models.Index(fields=['tag0'], name='knowledge_r_tag0_b3cf89_idx')],
            },
        ),
    ]
