# Generated by Django 5.2.5 on 2025-09-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_ragdocuments_ragchunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='kb_id',
            field=models.CharField(default='0', max_length=36),
        ),
    ]
