# Generated by Django 5.2.6 on 2025-09-09 06:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=36)),
                ('user_id', models.CharField(max_length=36)),
                ('kb_id', models.IntegerField(default=0)),
                ('sender', models.CharField(choices=[('user', '用户'), ('ai', 'AI')], max_length=20)),
                ('content', models.CharField(max_length=10000)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('chat_number', models.IntegerField()),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('title', models.CharField(default='新对话', max_length=200)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('chat_count', models.IntegerField(default=0)),
                ('ai_type', models.IntegerField(default=1)),
                ('kb_id', models.IntegerField(default=0)),
            ],
        ),
    ]
